// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxwbfduhveewbuluetpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4d2JmZHVodmVld2J1bHVldHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODkxNzYsImV4cCI6MjA2NDk2NTE3Nn0.xZYb93_kej1HPbQEKbSrBh_T0Zm27y8WoZ5oxuo7FeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);